#!/usr/bin/env bash
# Configurable deployment script that reads from .pi-config
set -euo pipefail

# Load configuration
if [ -f ../.pi-config ]; then
    source ../.pi-config
    RSPI="${PI_USER}@${PI_HOST}"
    echo "📝 Using Pi configuration: ${RSPI}"
else
    # Fallback to hardcoded value
    RSPI=pi@192.168.86.49
    echo "⚠️  No .pi-config found, using default: ${RSPI}"
fi

echo "📦 Deploying backend..."
rsync -az --delete --exclude 'node_modules' --exclude '.next' --exclude '__pycache__' backend/ $RSPI:~/apps/weather_app/backend/

echo "📦 Deploying frontend..."
rsync -az --delete --exclude 'node_modules' --exclude '.next' --exclude '.env.local' frontend/ $RSPI:~/apps/weather_app/frontend/

echo "📝 Setting up production environment..."
ssh $RSPI 'cat > ~/apps/weather_app/frontend/.env.production.local << EOF
# Production environment - auto-generated by deployment
NEXT_PUBLIC_API_URL=
EOF'

echo "📦 Deploying deployment scripts..."
rsync -az --delete deploy/ $RSPI:~/apps/weather_app/deploy/

echo "🔄 Updating dependencies and restarting services..."
ssh $RSPI 'cd ~/apps/weather_app/backend && uv sync && cd ~/apps/weather_app/frontend && npm install && npm run build && sudo systemctl restart weather.service && sudo systemctl restart weather-frontend.service'

echo "✅ Deployment complete!"
echo ""
echo "🌐 Access your dashboard at:"
echo "   http://${PI_HOST} (via nginx on port 80)"
echo "   or http://${PI_HOST}:3000 (direct Next.js)"
echo ""
